export default {
  saits: [
    { en: 'Biwaha', ne: 'बिवाह गर्ने साइत' },
    { en: 'Pasni', ne: 'पास्नी गर्ने साइतहरु' },
    { en: 'Bratabandha', ne: 'ब्रतबन्ध गर्ने साइत' },
    { en: 'Rudri', ne: 'रुद्री गर्ने साइत' },
    { en: 'Hom', ne: 'होम गर्ने साइत' },
    { en: 'Pasal', ne: 'पसल खोल्ने साइत' },
    { en: 'Home', ne: 'जग राख्न्ने साइत' },
    { en: 'Home Shift', ne: 'घर सर्ने साइत' },
  ],
  extraMonth: { en: 'Adhik ', ne: 'अधिक ' },
  days: [
    { ne: 'आइतवार', en: 'Sunday' },
    { ne: 'सोमवार', en: 'Monday' },
    { ne: 'मंगलवार', en: 'Tuesday' },
    { ne: 'बुधवार', en: 'Wednesday' },
    { ne: 'बिहीवार', en: 'Thursday' },
    { ne: 'शुक्रवार', en: 'Friday' },
    { ne: 'शनिवार', en: 'Saturday' },
  ],
  daysShort: [
    { ne: 'आइत', en: 'Sun' },
    { ne: 'सोम', en: 'Mon' },
    { ne: 'मंगल', en: 'Tue' },
    { ne: 'बुध', en: 'Wed' },
    { ne: 'बिही', en: 'Thu' },
    { ne: 'शुक्र', en: 'Fri' },
    { ne: 'शनि', en: 'Sat' },
  ],
  monthsAD: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  monthsBS: [
    { ne: 'वैशाख', en: 'Baisakh' },
    { ne: 'जेठ', en: 'Jestha' },
    { ne: 'असार', en: 'Ashar' },
    { ne: 'साउन', en: 'Shrawan' },
    { ne: 'भदौ', en: 'Bhadra' },
    { ne: 'असोज', en: 'Ashoj' },
    { ne: 'कार्तिक', en: 'Kartik' },
    { ne: 'मंसिर', en: 'Mangsir' },
    { ne: 'पौष', en: 'Poush' },
    { ne: 'माघ', en: 'Magh' },
    { ne: 'फागुन', en: 'Falgun' },
    { ne: 'चैत', en: 'Chaitra' },
  ],
  monthNS: [
    { ne: 'कछलाथ्व', en: 'Kachalatho' },
    { ne: 'कछलागा', en: 'Kachalaga' },
    { ne: 'थिंलाथ्व', en: 'Thiratho' },
    { ne: 'थिंलागा', en: 'Thilaga' },
    { ne: 'पोहेलाथ्व', en: 'Pohelatho' },
    { ne: 'पोहेलागा', en: 'Pohelaga' },
    { ne: 'सिल्लाथ्व', en: 'Sillatho' },
    { ne: 'सिल्लागा', en: 'Sillaga' },
    { ne: 'चिल्लाथ्व', en: 'Chillatho' },
    { ne: 'चिल्लागा', en: 'Chillaga' },
    { ne: 'चौलाथ्व', en: 'Chaulatho' },
    { ne: 'चौलागा', en: 'Chaulaga' },
    { ne: 'बछलाथ्व', en: 'Bachalatho' },
    { ne: 'बछलागा', en: 'Bachalaga' },
    { ne: 'तछलाथ्व', en: 'Tachalatho' },
    { ne: 'तछलागा', en: 'Tachalaga' },
    { ne: 'दिल्लाथ्व', en: 'Dillatho' },
    { ne: 'दिल्लागा', en: 'Dillaga' },
    { ne: 'गुँलाथ्व', en: 'Gunllatho' },
    { ne: 'गुँलागा', en: 'Gunllaga' },
    { ne: 'ञलाथ्व', en: 'Yalatho' },
    { ne: 'ञलगा', en: 'Yalaga' },
    { ne: 'कौलाथ्व', en: 'Kaulatho' },
    { ne: 'कौलागा', en: 'Kaulaga' },
    { ne: 'अनलाथ्व', en: 'Analatho' },
    { ne: 'अनलागा', en: 'Analaga' },
  ],
  tithis: [
    { ne: 'प्रतिपदा', en: 'Pratipada' },
    { ne: 'द्वितीया', en: 'Dwitiya' },
    { ne: 'तृतीया', en: 'Tritiya' },
    { ne: 'चतुर्थी', en: 'Chaturthi' },
    { ne: 'पञ्चमी', en: 'Panchami' },
    { ne: 'षष्ठी', en: 'Sasthi' },
    { ne: 'सप्तमी', en: 'Saptami' },
    { ne: 'अष्टमी', en: 'Astami' },
    { ne: 'नवमी', en: 'Nawami' },
    { ne: 'दशमी', en: 'Dashami' },
    { ne: 'एकादशी', en: 'Ekadashi' },
    { ne: 'द्वादशी', en: 'Dwadashi' },
    { ne: 'त्रयोदशी', en: 'Trayodashi' },
    { ne: 'चतुर्दशी', en: 'Chaturdashi' },
    { ne: 'पूर्णिमा', en: 'Purnima' },
    { ne: 'औंसी', en: 'Aunsi' },
  ],
  chandramas: [
    { ne: 'कार्तिक शुक्लपक्ष', en: 'Kartik Shuklapaksha' },
    { ne: 'मार्ग कृष्णपक्ष', en: 'Marga Krishnapaksha' },
    { ne: 'मार्ग शुक्लपक्ष', en: 'Marga Shuklapaksha' },
    { ne: 'पौष कृष्णपक्ष', en: 'Poush Krishnapaksha' },
    { ne: 'पौष शुक्लपक्ष', en: 'Poush Shuklapaksha' },
    { ne: 'माघ कृष्णपक्ष', en: 'Magh Krishnapaksha' },
    { ne: 'माघ शुक्लपक्ष', en: 'Magh Shuklapaksha' },
    { ne: 'फाल्गुण कृष्णपक्ष', en: 'Falgun Krishnapaksha' },
    { ne: 'फाल्गुण शुक्लपक्ष', en: 'Falgun Shuklapaksha' },
    { ne: 'चैत्र कृष्णपक्ष', en: 'Chaitra Krishnapaksha' },
    { ne: 'चैत्र शुक्लपक्ष', en: 'Chaitra Shuklapaksha' },
    { ne: 'वैशाख कृष्णपक्ष', en: 'Baisakh Krishnapaksha' },
    { ne: 'वैशाख शुक्लपक्ष', en: 'Baisakh Shuklapaksha' },
    { ne: 'ज्येष्ठ कृष्णपक्ष', en: 'Jestha Krishnapaksha' },
    { ne: 'ज्येष्ठ शुक्लपक्ष', en: 'Jestha Shuklapaksha' },
    { ne: 'आषाढ कृष्णपक्ष', en: 'Asadh Krishnapaksha' },
    { ne: 'आषाढ शुक्लपक्ष', en: 'Asadh Shuklapaksha' },
    { ne: 'श्रावण कृष्णपक्ष', en: 'Shrawan Krishnapaksha' },
    { ne: 'श्रावण शुक्लपक्ष', en: 'Shrawan Shuklapaksha' },
    { ne: 'भाद्र कृष्णपक्ष', en: 'Bhadra Krishnapaksha' },
    { ne: 'भाद्र शुक्लपक्ष', en: 'Bhadra Shuklapaksha' },
    { ne: 'आश्विन कृष्णपक्ष', en: 'Ashwin Krishnapaksha' },
    { ne: 'आश्विन शुक्लपक्ष', en: 'Ashwin Shuklapaksha' },
    { ne: 'कार्तिक कृष्णपक्ष', en: 'Kartik Krishnapaksha' },
  ],
}
